trainer: "BasicTrainer"
random_seed: 43

model:
  type: "efficientnet_b0"
  parameters:
    num_classes: 10
    pretrained: true

training:
  batch_size: 32
  num_epochs: 2
  loss_function:
    type: "CrossEntropyLoss"
    parameters: {}
  optimizer:
    type: "Adam"
    parameters:
      learning_rate: 0.001

metrics:
  - type: "Accuracy"
  - type: "Precision"
  - type: "Recall"
  - type: "F1Score"

callbacks:
  CSVLogging:
    parameters:
      csv_path: "dinamically/set/by/date.csv"
  EarlyStopping:
    parameters:
      monitor: "val_loss"
      patience: 3
      delta: 0.01
      verbose: true

data:
  name: "CIFAR10"
  dataset_path: "./data/processed"
  test_size: 0.2
  val_size: 0.1
  transforms:
    - type: "Resize"
      parameters:
        size: [240, 240]
    - type: "ToTensor"
    - type: "Normalize"
      parameters:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

paths:
  log_path: "./logs/"
  plot_path: "./outputs/figures/"
