trainer: "BasicTrainer"

random_seed: 43

model:
  name: efficientnet_b0
  num_classes: 10
  pretrained: true

training:
  batch_size: 32
  num_epochs: 2
  learning_rate: 0.001

data:
  name: "CIFAR10"
  dataset_path: "./data/processed"
  test_size: 0.2
  val_size: 0.1
  transforms:
    - name: Resize
      parameters:
        size: [224, 224]
    
    - name: ToTensor

paths:
  log_path: "./logs/"
  plot_path: "./outputs/figures/"
