trainer: "BasicTrainer"
random_seed: 43

model:
  type: "efficientnet_b1"
  parameters:
    num_classes: 394
    pretrained: true

training:
  batch_size: 32
  epochs:
    initial: 1
    fine_tuning: 1
  learning_rates:
    initial: 0.001
    fine_tuning: 0.0001
    final_fine_tuning: 0.00001
  freeze_until_layer: "classifier.1.weight"

metrics:
  - type: "Accuracy"
  - type: "Precision"
  - type: "Recall"
  - type: "F1Score"

data:
  name: "CarDataset"
  dataset_path: "./data/processed/BD-461"
  test_size: 0.2
  val_size: 0.1
  transforms:
    - type: "Resize"
      parameters:
        size: [240, 240]
    - type: "ToTensor"
      parameters: {}
    - type: "Normalize"
      parameters: {}

paths:
  log_path: "./logs/"
  plot_path: "./outputs/figures/"
