trainer: "BasicTrainer"

random_seed: 43

model:
  name: efficientnet_b1
  num_classes: 394
  pretrained: true

training:
  batch_size: 32
  num_epochs: 2   # Just maintained for compatibility
  initial_epochs: 1
  fine_tuning_epochs: 1
  learning_rate: 0.001  # Also maintained for compatibility
  fine_tuning_learning_rate: 0.0001
  freeze_until_layer: "classifier.1.weight"  # "fc.weight"
  final_fine_tuning_learning_rate: 0.00001

data:
  name: "CarDataset"
  dataset_path: "./data/processed/BD-461"
  test_size: 0.2
  val_size: 0.1
  transforms:
    - name: Resize
      parameters:
        size: [240, 240]
    
    - name: ToTensor

paths:
  log_path: "./logs/"
  plot_path: "./outputs/figures/"
