name: Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        environment-file: environment.yaml
        activate-environment: tda-nn-separability
        python-version: 3.10
        conda-channels: conda-forge

    - name: Install Dependencies
      run: |
        conda info
        conda list

    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest tests/
